### PR TITLE
treat offsets skipped due to kafka transactions as comitted

### LINKED ISSUE #4451: KafkaSource doesn't commit offsets if events produced with Kafka transactions
**Describe the bug**

The eventing-kafka-broker dispatcher OffsertManager expects all offsets to contain events. With transactions, some of the offsets are skipped.

This causes the KafkaSource dispatcher to stop committing offsets, as it waits for the "skipped" offsets. 

Such "skipped" offsets are produced by producers using kafka transactions. 

 **Expected behavior**
KafkaSource should continue to dispatch events if there is a gap in offsets because of Kafka transactions.

 **To Reproduce**
https://gist.github.com/maschmid/442dd9a6bee10186f042fdb026ef5b95

 **Knative release version**
1.16

 **Additional context**

### PR DESCRIPTION
**Pull request by maschmid**
Fixes #4451

## Proposed Changes

- introduce OffsetSkippingCloudEvent to represent a "skipped offset"
- make RecordDispatcher discard OffsetSkippingCloudEvents
- add a kafka_source test variant with transactional id to verify KafkaSource behavior with a topic in which events are produced with Kafka transactions.

**Release Note**

```release-note
Fixes a KafkaSource issue, where the kafka-source-dispatcher would stop committing offsets if the events were produced by a producer using Kafka transactions. 
```

**Docs**

### CODE REVIEW

File: data-plane/dispatcher/src/main/java/dev/knative/eventing/kafka/broker/dispatcher/impl/RecordDispatcherImpl.java [hunk 1]
```diff
@@ -176,6 +178,17 @@ public Future<Void> dispatch(ConsumerRecord<Object, CloudEvent> record) {
...
 
+        if (record.value() instanceof OffsetSkippingCloudEvent) {
+            incrementSkippedOffset(recordContext);
+            final var msg = String.format(
+                    "Skipping offset topic %s, partition %d, offset %d",
+                    record.topic(), record.partition(), record.offset());
+            logger.debug(msg);
+            recordDispatcherListener.recordReceived(record);
+            recordDispatcherListener.recordDiscarded(record);
+            return Future.failedFuture(msg);
```
Comment (Cali0707) [inline data-plane/dispatcher/src/main/java/dev/knative/eventing/kafka/broker/dispatcher/impl/RecordDispatcherImpl.java:189]: Is there a reason why we want to fail this future? IMO, since we are just skipping it, this is more of a "success" than not...

But, I also have not looked at this code in while, so I could be wrong.

Any thoughts @maschmid @creydr ?

**Comment by maschmid** [comment]
https://prow.knative.dev/view/gs/knative-prow/pr-logs/pull/knative-extensions_eventing-kafka-broker/4452/reconciler-tests-keda_eventing-kafka-broker_main/1947650393974509568 
```
feature.go:227: Warning, failed to delete test-sooyarik/kafka-source-utxqblxg of GVR: sources.knative.dev/v1, Resource=kafkasources: conversion webhook for sources.knative.dev/v1beta1, Kind=KafkaSource failed: Post "[https://kafka-webhook-eventing.knative-eventing.svc:443/resource-conversion?timeout=30s](https://kafka-webhook-eventing.knative-eventing.svc/resource-conversion?timeout=30s)": EOF
```

we need to start retrying those deletions if we want to keep it running with the chaosduck randomly killing the webhooks... 

/test reconciler-tests-keda

**Comment by dsimansk** [comment]
@Cali0707 @maschmid wanna merge into 1.19 release?

**Comment by maschmid** [comment]
Following the discussion on  https://github.com/openshift-knative/eventing-kafka-broker/pull/1838#issuecomment-3048077312  , we also set kafkasource isolation.level to `read_committed`

**Comment by maschmid** [comment]
https://prow.knative.dev/view/gs/knative-prow/pr-logs/pull/knative-extensions_eventing-kafka-broker/4452/upgrade-tests_eventing-kafka-broker_main/1948405557710819328 

I see 
> I 16:04:09.178 kafka-sink-receiver-66b5d54d8b-52qwg kafka-sink-receiver {"@timestamp":"2025-07-24T16:04:09.160488223Z","@version":"1","message":"Resource not found path=/test-gppezwgp/kafka-sink-naduelgq host=kafka-sink-ingress.knative-eventing.svc:8080 hostHeader=kafka-sink-ingress.knative-eventing.svc:8080","logger_name":"dev.knative.eventing.kafka.broker.receiver.impl.ReceiverVerticle","thread_name":"vert.x-eventloop-thread-1","level":"WARN","level_value":30000,"path":"/test-gppezwgp/kafka-sink-naduelgq","host":"kafka-sink-ingress.knative-eventing.svc:8080","hostHeader":"kafka-sink-ingress.knative-eventing.svc:8080"}

which is after KafkaSinkSourceBinaryEventFeature finished, so it seems some attempts at sending the event was there after the  timeout. Hard to say without the logs from test-gppezwgp 

https://prow.knative.dev/view/gs/knative-prow/pr-logs/pull/knative-extensions_eventing-kafka-broker/4452/integration-tests_eventing-kafka-broker_main/1948405557593378816 , 

TestSacuraSinkSourceJob seems to be flaky.

/retest-required

**Comment by maschmid** [comment]
https://prow.knative.dev/view/gs/knative-prow/pr-logs/pull/knative-extensions_eventing-kafka-broker/4452/integration-tests_eventing-kafka-broker_main/1949838487586869248 

>     kafka_source.go:212: Assert in range failed: expected <= 1 events, saw 2 

Duplicate event in TestKafkaSourceConsumesMsgNoEvent/3/no_event_no_content_type-v1 

In https://storage.googleapis.com/knative-prow/pr-logs/pull/knative-extensions_eventing-kafka-broker/4452/integration-tests_eventing-kafka-broker_main/1949838487586869248/artifacts/new-logs/kafka-source-dispatcher-1-kafka-source-dispatcher-14:49:27.log  

we see that the partition was revoked in 
```
{"@timestamp":"2025-07-28T14:53:58.292992543Z","@version":"1","message":"Received revoke partitions for consumer context={topics=[b04aa3bf-d29f-46d8-8034-b55845aee03c], consumerGroup='a3406bc9-05ae-455f-b77b-f85e44cc71bb', reference=uuid: \"8b164b2c-44ff-414f-bf0f-d5b05ad63306\"\nnamespace: \"eventing-e2e16\"\nname: \"e2e-kafka-source-no-event-no-content-type-v1\"\nkind: \"KafkaSource\"\ngroupVersion: \"sources.knative.dev/v1\"\n} partitions=[b04aa3bf-d29f-46d8-8034-b55845aee03c-0, b04aa3bf-d29f-46d8-8034-b55845aee03c-1, b04aa3bf-d29f-46d8-8034-b55845aee03c-2, b04aa3bf-d29f-46d8-8034-b55845aee03c-3, b04aa3bf-d29f-46d8-8034-b55845aee03c-4]","logger_name":"dev.knative.eventing.kafka.broker.dispatcher.main.ConsumerVerticleContext","thread_name":"Thread-33","level":"INFO","level_value":20000,"context":{},"partitions":[{},{},{},{},{}]}
```
just after "Sending event", and then it was assigned again. 

The Partition revoked handler failed 

> {"@timestamp":"2025-07-28T14:54:01.992395557Z","@version":"1","message":"Partition revoked handler failed context={topics=[b04aa3bf-d29f-46d8-8034-b55845aee03c], consumerGroup='a3406bc9-05ae-455f-b77b-f85e44cc71bb', reference=uuid: \"8b164b2c-44ff-414f-bf0f-d5b05ad63306\"\nnamespace: \"eventing-e2e16\"\nname: \"e2e-kafka-source-no-event-no-content-type-v1\"\nkind: \"KafkaSource\"\ngroupVersion: \"sources.knative.dev/v1\"\n} partitions=[b04aa3bf-d29f-46d8-8034-b55845aee03c-5, b04aa3bf-d29f-46d8-8034-b55845aee03c-6, b04aa3bf-d29f-46d8-8034-b55845aee03c-7, b04aa3bf-d29f-46d8-8034-b55845aee03c-8, b04aa3bf-d29f-46d8-8034-b55845aee03c-9]","logger_name":"dev.knative.eventing.kafka.broker.dispatcher.main.ConsumerVerticleContext","thread_name":"Thread-51","level":"WARN","level_value":30000,"context":{},"partitions":[{},{},{},{},{}]}


(This kind of issue should be fixed by https://github.com/knative-extensions/eventing-kafka-broker/pull/4461   (although, it will still be possible to get duplicate events on partition revoked, as the in-flight events will be resend if the partiton is revoked before the event dispatch finished and comitted))

/test integration-tests

**Comment by maschmid** [comment]
https://prow.knative.dev/view/gs/knative-prow/pr-logs/pull/knative-extensions_eventing-kafka-broker/4452/integration-tests_eventing-kafka-broker_main/1949880668305494016

sacura-sink-source `lost count (accepted but not received): 18000 - 17349 = 710` quite close now

We should probably either deploy the sacura-sink-source after all the other tests (to not have that many scale ups/downs of the kafka-source-dispatcher caused by the other tests), or increase the timeout to account for the delay caused by all the rebalancing... 

/test integration-tests

**Comment by maschmid** [comment]
>     trigger.go:213: failed to update resource Operation cannot be fulfilled on triggers.eventing.knative.dev "trigger-vlsmtagb": the object has been modified; please apply your changes to the latest version and try again - Resource:

/test reconciler-tests-namespaced-broker

**Comment by maschmid** [comment]
>     steps.go:47: sources.knative.dev/v1, Resource=kafkasources did not become ready, conversion webhook for sources.knative.dev/v1beta1, Kind=KafkaSource failed: Post "https://kafka-webhook-eventing.knative-eventing.svc:443/resource-conversion?timeout=30s": EOF

/test reconciler-tests

**Comment by Cali0707** [comment]
`     control_plane.go:271: channel was not ready, reason: ProbeStatus `

/test channel-reconciler-tests-sasl-ssl
