### PR TITLE
Fix multiple time Promise complete problem

### LINKED ISSUE #3309: Loom:  Result is already complete
**Describe the bug**

We're getting this error on `LoomKafkaConsumerTest` https://github.com/knative-extensions/eventing-kafka-broker/actions/runs/5972439790/job/16202977280?pr=3308:
```
Error: Exception in thread "" java.lang.IllegalStateException: Result is already complete
	at io.vertx.core.Promise.fail(Promise.java:90)
	at dev.knative.eventing.kafka.broker.dispatcherloom.LoomKafkaConsumer.lambda$subscribe$7(LoomKafkaConsumer.java:174)
	at dev.knative.eventing.kafka.broker.dispatcherloom.LoomKafkaConsumer.processTaskQueue(LoomKafkaConsumer.java:65)
	at java.base/java.lang.VirtualThread.run(VirtualThread.java:305)
	at java.base/java.lang.VirtualThread$VThreadContinuation.lambda$new$0(VirtualThread.java:177)
	at java.base/jdk.internal.vm.Continuation.enter0(Continuation.java:327)
	at java.base/jdk.internal.vm.Continuation.enter(Continuation.java:320)
``` 

We should investigate why the promise is completed multiple times

 **Expected behavior**

No such error and test pass

 **To Reproduce**

Run the `LoomKafkaConsumerTest` test

 **Knative release version**
`main`

 **Additional context**

### PR DESCRIPTION
**Pull request by debasishbsws**
Fixes #3309

From my inspection what might happening here is that After we are close the consumer, though we are failing the corresponding task promise still taskRunnerThread is still taking the task as we are not returning from the function.
https://github.com/knative-extensions/eventing-kafka-broker/blob/1e369784b4161dfb9a35eabe96b0db618991213b/data-plane/dispatcher-loom/src/main/java/dev/knative/eventing/kafka/broker/dispatcherloom/LoomKafkaConsumer.java#L55-L59

Other than that I also saw a exception while we are trying close the consumer. Though it is the Interrupted exception that is expected, but there is a possibility that the `consumer.close()` method fail. and we try to complete it again while we stop taskRunnerThread here
https://github.com/knative-extensions/eventing-kafka-broker/blob/1e369784b4161dfb9a35eabe96b0db618991213b/data-plane/dispatcher-loom/src/main/java/dev/knative/eventing/kafka/broker/dispatcherloom/LoomKafkaConsumer.java#L106-L112

/cc @pierDipi

### CODE REVIEW

File: data-plane/dispatcher-loom/src/main/java/dev/knative/eventing/kafka/broker/dispatcherloom/LoomKafkaConsumer.java [hunk 1]
```diff
@@ -105,10 +107,10 @@ public Future<Void> close() {
                 }
                 taskRunnerThread.interrupt();
                 taskRunnerThread.join();
-                promise.complete();
+                promise.tryComplete();
```
Comment (matzew) [inline data-plane/dispatcher-loom/src/main/java/dev/knative/eventing/kafka/broker/dispatcherloom/LoomKafkaConsumer.java:110]: is this behavioral change (try complete - instead of "force complete"), due to the loom env?

Comment (debasishbsws) [reply data-plane/dispatcher-loom/src/main/java/dev/knative/eventing/kafka/broker/dispatcherloom/LoomKafkaConsumer.java:110]: No, It is not a behavioral change, it is only to make sure we do not mark the promise complete if it was already completed.

**Review by pierDipi — APPROVED** [review]
Thanks @debasishbsws !

/lgtm
/approve
