### PR TITLE
fix: kafka controller does not panic on invalid kafka client config

### LINKED ISSUE #3935: Wrong kafka source configuration results in SIGSEGV instead of useful error message
**Describe the bug**
Wrong kafka source configuration results in SIGSEGV instead of useful error message.

 **Expected behavior**
There should be a clear error message instead of a SIGSEGV.

 **To Reproduce**
Use `plain` instead of `PLAIN` for `net.sasl.type`.

 **Knative release version**
1.14.5

 **Additional context**
Log output:
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x1c6f119]

goroutine 532 [running]:
knative.dev/eventing-kafka-broker/control-plane/pkg/reconciler/consumergroup.(*Reconciler).reconcileInitialOffset(0xc000142000, {0x261e1d8, 0xc006ea7c20}, 0xc00068b508)
knative.dev/eventing-kafka-broker/control-plane/pkg/reconciler/consumergroup/consumergroup.go:599 +0x2d9
knative.dev/eventing-kafka-broker/control-plane/pkg/reconciler/consumergroup.(*Reconciler).ReconcileKind(0xc000142000, {0x261e1d8, 0xc006ea7c20}, 0xc00068b508)
knative.dev/eventing-kafka-broker/control-plane/pkg/reconciler/consumergroup/consumergroup.go:196 +0x131
knative.dev/eventing-kafka-broker/control-plane/pkg/client/internals/kafka/injection/reconciler/eventing/v1alpha1/consumergroup.(*reconcilerImpl).Reconcile(0xc0004aa5a0, {0x261e1d8, 0xc006ea7bf0}, {0xc006eae4c0, 0x31})
knative.dev/eventing-kafka-broker/control-plane/pkg/client/internals/kafka/injection/reconciler/eventing/v1alpha1/consumergroup/reconciler.go:240 +0x52b
knative.dev/pkg/controller.(*Impl).processNextWorkItem(0xc0001b3980)
knative.dev/pkg@v0.0.0-20240416145024-0f34a8815650/controller/controller.go:542 +0x508
knative.dev/pkg/controller.(*Impl).RunContext.func3()
knative.dev/pkg@v0.0.0-20240416145024-0f34a8815650/controller/controller.go:491 +0x59
created by knative.dev/pkg/controller.(*Impl).RunContext in goroutine 506
knative.dev/pkg@v0.0.0-20240416145024-0f34a8815650/controller/controller.go:489 +0x325
```

I think this is cause by calling `defer kafkaClusterAdminClient.Close()` even if no client was created (https://github.com/knative-extensions/eventing-kafka-broker/blob/main/control-plane/pkg/reconciler/consumergroup/consumergroup.go#L602).

### PR DESCRIPTION
**Pull request by Cali0707**
Fixes #3935

## Proposed Changes

- Only defer closing the cluster admin if it is not nil
- Check that the configs map exists before accessing a value in it

**Release Note**

```release-note
The kafka controller does not panic on invalid kafka client configmaps anymore
```

### CODE REVIEW

File: control-plane/pkg/reconciler/consumergroup/consumergroup.go [hunk 1]
```diff
@@ -596,13 +600,17 @@ func (r *Reconciler) reconcileInitialOffset(ctx context.Context, cg *kafkaintern
 		return fmt.Errorf("failed to get secret for Kafka cluster auth: %w", err)
 	}
 
+	if cg.Spec.Template.Spec.Configs.Configs == nil {
+		return fmt.Errorf("no consumer config supplied, unable to get bootstrap.servers")
+	}
```
Comment (pierDipi) [inline control-plane/pkg/reconciler/consumergroup/consumergroup.go:605]: This seems to be better suited for `Validate` so that it gets rejected from the beginning ?

File: control-plane/pkg/reconciler/consumergroup/consumergroup.go [hunk 2]
```diff
@@ -301,13 +301,17 @@ func (r *Reconciler) deleteConsumerGroupMetadata(ctx context.Context, cg *kafkai
...
```
Comment (pierDipi) [inline control-plane/pkg/reconciler/consumergroup/consumergroup.go:306]: Same for this one?

File: control-plane/pkg/apis/internals/kafka/eventing/v1alpha1/consumer_group_validation.go [hunk 3]
```diff
@@ -57,6 +57,9 @@ func (cts *ConsumerTemplateSpec) Validate(ctx context.Context) *apis.FieldError
 		cts.Spec.Delivery.Validate(specCtx).ViaField("delivery"),
 		cts.Spec.Subscriber.Validate(specCtx).ViaField("subscriber"),
 	)
+	if cts.Spec.Configs.Configs == nil {
+		err = err.Also(apis.ErrMissingField("spec.configs"))
```
Comment (matzew) [inline control-plane/pkg/apis/internals/kafka/eventing/v1alpha1/consumer_group_validation.go:61]: can we test the missing config ?

**Comment by Cali0707** [comment]
@pierDipi is it worth backporting to 1.13 with the 1.15 release going out this week?
